### ISSUE TITLE
Whatevergreen.kext absence

### ISSUE THREAD

**Issue by MAM-SYS** [cxyzhangbin/Hackintosh-B760M-13600KF-6650XT#2]
I appreciate your willingness to share your EFI file, as it has been incredibly helpful.
As a novice in the Hackintosh community and the process of creating a proper EFI file, I have a question regarding the absence of the WhateverGreen.kext file in your kext directory.
Could you provide any insight into why this might be the case?
My goal is to enable my AMD RX 6800 XT GPU on my system, and I understand that the WhateverGreen.kext is essential for this purpose. Thank you once again for your assistance.

**Comment by cxyzhangbin** [comment]
> I appreciate your willingness to share your EFI file, as it has been incredibly helpful. As a novice in the Hackintosh community and the process of creating a proper EFI file, I have a question regarding the absence of the WhateverGreen.kext file in your kext directory. Could you provide any insight into why this might be the case? My goal is to enable my AMD RX 6800 XT GPU on my system, and I understand that the WhateverGreen.kext is essential for this purpose. Thank you once again for your assistance.

Hi bro,If your GPU is AMD, you don't need the WhateverGreen.kext file,beacause it is primarily used for Intel graphics support.If you don' t start MacOS or GPU don't work in MacOS, please detailed description.I will do my best for help you.
